
services:
  app:
    container_name: flue-tecnologia-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: fluetecnologia/app
    restart: always
    working_dir: /var/www/
    command: sh ./wait-for-db.sh mysql python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fluetecnologia

  mysql:
    container_name: flue-tecnologia-mysql
    image: mysql:8.0
    platform: linux/amd64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysql -u${DB_USER} -p${DB_PASSWORD} -e 'SELECT 1;' ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - fluetecnologia
    command: --default-authentication-plugin=mysql_native_password

networks:
  fluetecnologia:
    driver: bridge
