# Generated by Django 5.2.14 on 2026-05-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricker_app', '0006_alter_product_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_value',
            new_name='expected_sale_value',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('sold', 'Vendido')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_products',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='bricker_app.product'),
        ),
    ]
